name: Update README

on:
  push:
    branches:
      - main  # যদি আপনার ব্রাঞ্চের নাম আলাদা হয় তবে এখানে পরিবর্তন করুন

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # v3 এ আপডেট করা হয়েছে

      - name: Update README with most used languages
        run: |
          echo "## My Most Used Languages" >> README.md
          echo "![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=Abubokkor98&layout=compact&theme=dark)" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with most used languages" || echo "No changes to commit"
          git push || echo "Push failed"
