name: Update README with Most Used Languages and Commit Count

on:
  push:
    branches:
      - main  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Update README with most used languages and commit count
        run: |
          LANG_SECTION_START="### 📊 GitHub Stats:"
          LANG_SECTION_END="</p>"

          # New content for the 'Most Used Languages' and 'Total Commits' section
          NEW_LANG_SECTION="<p align=\"center\">\n  <img src=\"https://github-readme-stats.vercel.app/api/top-langs/?username=Abubokkor98&layout=compact&theme=dark\" alt=\"Top Languages\" />\n  <img src=\"https://github-readme-stats.vercel.app/api?username=Abubokkor98&count_private=true&show_icons=true&theme=dark&include_all_commits=true\" alt=\"Total Commits\" />\n</p>"

          # Find and replace between LANG_SECTION_START and LANG_SECTION_END using awk
          awk -v start="$LANG_SECTION_START" -v end="$LANG_SECTION_END" -v new_section="$NEW_LANG_SECTION" \
          'BEGIN {in_section=0} 
          {if ($0 ~ start) {print; print new_section; in_section=1} 
          else if ($0 ~ end) {in_section=0} 
          else if (!in_section) {print}}' README.md > README.tmp && mv README.tmp README.md

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with most used languages and total commits" || echo "No changes to commit"
          git push || echo "Push failed"
